---
- name: Get information of the system
  ansible.builtin.package_flacts:
   manager: auto

- name: Install package for PostgreSQL
  ansible.builtin.package:
   name: "{{item}}"
   state: present
  loop: 
   - postgresql
   - postgresql-server
   - postgresql-contrib
   - postgresql-libs
   - python3-psycopg2

- name: Check if PostgreSQL is initialized
  ansible.builtin.stat:
   path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: Initialize PostgreSQL
  ansible.builtin.shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: Start and enable service
  ansible.builtin.service:
   name: postgresql
   state: started
   enabled: true

- name: Create database bd_example
  become: true
  postgresql_db:
   name: "{{database_name}}"

- name: Create user in the bd_example
  become: true
  postgresql_user:
   db: "{{database_name}}"
   name: "{{database_user}}"
   password: admin*
   priv: ALL
   state: present

- name: Ensure that the user has access to the database
  become_user: "{{database_user}}"
  become: true
  postgresql_user:
   db: "{{database_name}}"
   name: "{{database_user}}"
   priv: ALL
   state: present

- name: Allow md5 connection for database user
  become_user: "{{database_user}}"
  become: true
  lineinfile:
    dest: /etc/postgresql/9.6/main/pg_hba.conf
    state: present
    regexp: '^#*.*{{ database_name }}.*'
    line: 'host    {{ database_name }}    {{ database_user }}    0.0.0.0/0    md5'
    backrefs: yes
    insertafter: '^# IPv4 local connections:'
    validate: '/usr/sbin/postgresql --check --global-config-only'
    backup: yes

- name: Create database backup
  become_user: "{{ database_user }}"
  become: true
  command: pg_dump {{database_name}} > /tmp/backup_db

- name: Reboot the server 
  ansible.builtin.reboot:
    reboot_timeout: 3600

- name: Change the hostname of the machine
  become: true
  ansible.builtin.hostname:
    name: hostname_test

- name: Print IP and hostname
  ansible.builtin.debug:
    msg: "La dirección IP del servidor es {{ ansible_default_ipv4.address }} y el hostname es {{ ansible_hostname }}"





