---
- name: Get information of the system
  ansible.builtin.package_flacts:
   manager: auto

- name: Install package for PostgreSQL
  ansible.builtin.package:
   name: "{{item}}"
   state: present
  loop: 
   - postgresql
   - postgresql-server
   - postgresql-contrib
   - postgresql-libs
   - python3-psycopg2

- name: Check if PostgreSQL is initialized
  ansible.builtin.stat:
   path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: Initialize PostgreSQL
  ansible.builtin.shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: Start and enable service
  ansible.builtin.service:
   name: postgresql
   state: started
   enabled: true

- name: Create database bd_example
  become_user: postgres
  become: true
  postgresql_db:
   name: bd_example

- name: Create user in the bd_example
  become_user: postgres
  become: true
  postgresql_user:
   db: bd_example
   name: admin
   password: admin*
   priv: ALL
   state: present






